name: trufi_core
description: A Flutter Plugin for Public Transport.
version: 1.0.0
publish_to: 'none'
repository: https://github.com/Reksa-ggwp/angkot-core

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  cupertino_icons: ^1.0.2
  app_review: ^2.1.2+1
  async: ^2.9.0
  async_executor: ^0.0.2
  cached_network_image: ^3.2.2
  collection: ^1.16.0
  device_info_plus: ^4.1.2
  device_info_plus_platform_interface: ^3.0.0
  diff_match_patch: ^0.4.1
  equatable: ^2.0.5
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter  
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_map: ^3.0.0
  flutter_svg: ^1.1.5
  geolocator: ^9.0.2
  graphql: ^5.1.1
  hive: ^2.2.3
  http: ^0.13.5
  intl: ^0.17.0
  latlong2: ^0.8.1
  package_info_plus: ^1.4.3+1
  flutter_map_line_editor: ^5.0.0
  back_button_interceptor: ^6.0.2
  flutter_map_marker_cluster: ^1.1.0
  path_provider: ^2.0.11
  provider: ^6.0.3
  routemaster: ^1.0.1
  rxdart: ^0.27.5
  share_plus: ^4.4.0
  synchronized: ^3.0.0+3
  uni_links: ^0.5.1
  uuid: ^3.0.5
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  lodash_flutter: ^0.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/data/
    - assets/images/
  # - assets/data/POIs/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
